#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input())
 
    #Convert to binary 
    binary_array = []
    i = 0
    while n > 0:
        binary_array.insert(0, str(n % 2))
        n = n // 2
        i += 1
    binary_number = ''
    binary_number = binary_number.join(binary_array)
    #print(binary_number)
    
    #Search in the results for the longest run of 1's 
    ones_array = re.findall('1+', binary_number)
    longest = max(ones_array, key=len)
    print(len(longest))





